# Site settings
title: Mercato
email: info@bikeandbuild.org
title: Pizzeria Mercato
description: > # this means to ignore newlines until "baseurl:"
  Pizzeria Mercato
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pizza.morf-studio.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
